### PR TITLE
update pip requirements

### PR DESCRIPTION
**Pull request by lgarithm**

### CODE REVIEW

**Comment by lgarithm** [comment]
@boldjoel can we use `pip install pycocotools` instead of building it from source?

**Comment by zsdonghao** [comment]
@lgarithm I remember we tried, it will have problem.

**Comment by lgarithm** [comment]
@zsdonghao was the problem like https://travis-ci.org/tensorlayer/openpose/builds/420842885?

**Comment by zsdonghao** [comment]
@lgarithm I don't remember the details.
When using `pip install pycocotools` , we can't import it.

**Comment by lgarithm** [comment]
@zsdonghao as far as I've tried, I should work.
But you need `pip install cpython` before `pip install pycocotools`, 
like https://github.com/tensorlayer/openpose/pull/7/files#diff-354f30a63fb0907d4ad57269548329e3R12

If this is confirmed, we can remove 3.1 of https://github.com/tensorlayer/openpose#3-preparation

**Comment by zsdonghao** [comment]
@lgarithm wow, it works on my mac.. you are right. 
can you run the code in this repo?

**Comment by lgarithm** [comment]
@zsdonghao I need this file [data/test.jpeg](https://github.com/tensorlayer/openpose/blob/master/inference.py#L45), where can I download it?

**Comment by zsdonghao** [comment]
@lgarithm should we tell people in readme that this repo still under development?

**Pull request merged**
